dist: trusty
language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.0
services: 
  - redis
  - postgresql
  - elasticsearch
  - rabbitmq
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
sudo: required
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create user commodity login password 'commodity'"
  - psql -U postgres -c "create database commodity_test owner commodity"
  - rabbitmqctl add_user local local
  - rabbitmqctl set_user_tags local administrator
  - rabbitmqctl set_permissions -p / local ".*" ".*" ".*"
  - sleep 10
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix compile
script:
- MIX_ENV=test mix do ecto.reset, test
- mix coveralls.travis